# Generated by Django 4.2.14 on 2024-07-19 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_remove_pokemon_body_remove_pokemon_created_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pokemon",
            name="pokedex_number",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
